Repository SwissTierrasColombia/Asistente-LADM-COL, pull requests merged in 2020-04, with the labels that each got.

#312 Update descriptions in etl_snc model
  asistente_ladm_col/config/general_config.py
  asistente_ladm_col/core/supplies/etl_snc.py
  asistente_ladm_col/gui/supplies/snc_data_sources_widget.py
  asistente_ladm_col/gui/supplies/wiz_supplies_etl.py
  asistente_ladm_col/lib/processing/models/model_etl_supplies_snc_ladm_col.model3
  asistente_ladm_col/resources/etl/ficha_matriz.csv
  asistente_ladm_col/resources/etl/ficha_matriz_predio.csv
  asistente_ladm_col/resources/etl/ficha_matriz_torre.csv
  asistente_ladm_col/resources/etl/unidad_construccion.csvt
  asistente_ladm_col/ui/supplies/snc_data_source_widget.ui
Labels: under review

#316 [processing] Optimize Insert Features to Layer
  asistente_ladm_col/asistente_ladm_col_plugin.py
  asistente_ladm_col/config/layer_config.py
  asistente_ladm_col/config/mapping_config.py
  asistente_ladm_col/config/refactor_fields_mappings.py
  asistente_ladm_col/core/app_core_interface.py
  asistente_ladm_col/gui/dialogs/dlg_import_from_excel.py
  asistente_ladm_col/gui/dialogs/dlg_settings.py
  asistente_ladm_col/gui/toolbar.py
  asistente_ladm_col/gui/wizards/operation/dlg_create_group_party_operation.py
  asistente_ladm_col/i18n/Asistente-LADM_COL_es.ts
  asistente_ladm_col/lib/db/db_connector.py
  asistente_ladm_col/lib/db/gpkg_connector.py
  asistente_ladm_col/lib/db/pg_connector.py
  asistente_ladm_col/lib/processing/algs/InsertFeaturesToLayer.py
  asistente_ladm_col/tests/test_all_models.py
  asistente_ladm_col/tests/test_ant_model.py
  asistente_ladm_col/tests/test_cadastral_form_model.py
  asistente_ladm_col/tests/test_cadastral_manager_data_model.py
  asistente_ladm_col/tests/test_copy_csv_points_to_db.py
  asistente_ladm_col/tests/test_integration_supplies_model.py
  asistente_ladm_col/tests/test_operation_model.py
  asistente_ladm_col/tests/test_reference_cartography_model.py
  asistente_ladm_col/tests/test_snr_data_model.py
  asistente_ladm_col/tests/test_valuation_model.py
  asistente_ladm_col/ui/dialogs/dlg_settings.ui
Labels: Ready for tests

#326 [fix] Redraw layer after field mapping import data
  asistente_ladm_col/app_interface.py
  asistente_ladm_col/core/app_core_interface.py
  asistente_ladm_col/gui/app_gui_interface.py
  asistente_ladm_col/gui/wizards/operation/wiz_create_points_operation.py
  asistente_ladm_col/gui/wizards/operation/wiz_create_right_of_way_operation.py
  asistente_ladm_col/gui/wizards/spatial_wizard_factory.py
  asistente_ladm_col/gui/wizards/wizard_factory.py
  asistente_ladm_col/utils/decorators.py
Labels: Expecting adjustments
